apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  type: ClusterIP # Linea cambiada para que sea de tipo LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
